const coursesData = [
    {
      _id: "dsa-fundamentals",
      title: "Data Structures & Algorithms",
      description: "Master the fundamentals of DSA with comprehensive coverage of all important topics",
      instructor: "Dr. Sarah Johnson",
      duration: "12 weeks",
      level: "Beginner to Advanced",
      rating: 4.8,
      studentsEnrolled: 15420,
      price: 99,
      originalPrice: 199,
      thumbnail: "/placeholder.svg?height=200&width=300",
      tags: ["Programming", "Algorithms", "Data Structures"],
      category: "Computer Science",
      isActive: true,
      comingSoon: false,
      concepts: [
        {
          id: 1,
          title: "Arrays & Strings",
          description: "Learn about arrays, strings, and basic operations",
          duration: "2 hours",
          completed: false,
          topics: [
            {
              id: 1,
              title: "Introduction to Arrays",
              type: "video",
              duration: "15 min",
              videoUrl: "https://www.youtube.com/watch?v=55l-aZ7_F24",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 2,
              title: "Array Operations",
              type: "video",
              duration: "20 min",
              videoUrl: "https://www.youtube.com/watch?v=QJNwK2uJyGs",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 3,
              title: "String Manipulation",
              type: "article",
              duration: "10 min",
              content: "Comprehensive guide to string operations...",
              completed: false,
            },
            {
              id: 4,
              title: "Array Problems Practice",
              type: "quiz",
              duration: "30 min",
              questions: 10,
              completed: false,
            },
          ],
        },
        {
          id: 2,
          title: "Linked Lists",
          description: "Understanding linked lists and their implementations",
          duration: "3 hours",
          completed: false,
          topics: [
            {
              id: 1,
              title: "Introduction to Linked Lists",
              type: "video",
              duration: "18 min",
              videoUrl: "https://www.youtube.com/watch?v=WwfhLC16bis",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 2,
              title: "Singly Linked Lists",
              type: "video",
              duration: "25 min",
              videoUrl: "https://www.youtube.com/watch?v=R9PTBwOzceo",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 3,
              title: "Doubly Linked Lists",
              type: "video",
              duration: "22 min",
              videoUrl: "https://www.youtube.com/watch?v=8kptHdreaTA",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 4,
              title: "Linked List Problems",
              type: "coding",
              duration: "45 min",
              problems: 5,
              completed: false,
            },
          ],
        },
        {
          id: 3,
          title: "Stacks & Queues",
          description: "Learn about stacks, queues, and their applications",
          duration: "2.5 hours",
          completed: false,
          topics: [
            {
              id: 1,
              title: "Stack Implementation",
              type: "video",
              duration: "20 min",
              videoUrl: "https://www.youtube.com/watch?v=F1F2imiOJfk",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 2,
              title: "Queue Implementation",
              type: "video",
              duration: "18 min",
              videoUrl: "https://www.youtube.com/watch?v=okr-XE8yTO8",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 3,
              title: "Stack & Queue Applications",
              type: "article",
              duration: "15 min",
              content: "Real-world applications of stacks and queues...",
              completed: false,
            },
          ],
        },
        {
          id: 4,
          title: "Trees & Binary Search Trees",
          description: "Understanding tree data structures and BST operations",
          duration: "4 hours",
          completed: false,
          topics: [
            {
              id: 1,
              title: "Introduction to Trees",
              type: "video",
              duration: "25 min",
              videoUrl: "https://www.youtube.com/watch?v=qH6yxkw0u78",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 2,
              title: "Binary Search Trees",
              type: "video",
              duration: "30 min",
              videoUrl: "https://www.youtube.com/watch?v=pYT9F8_LFTM",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 3,
              title: "Tree Traversals",
              type: "video",
              duration: "28 min",
              videoUrl: "https://www.youtube.com/watch?v=9RHO6jU--GU",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
          ],
        },
        {
          id: 5,
          title: "Sorting Algorithms",
          description: "Master various sorting algorithms and their complexities",
          duration: "3 hours",
          completed: false,
          topics: [
            {
              id: 1,
              title: "Bubble Sort & Selection Sort",
              type: "video",
              duration: "22 min",
              videoUrl: "https://www.youtube.com/watch?v=xli_FI7CuzA",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 2,
              title: "Merge Sort",
              type: "video",
              duration: "25 min",
              videoUrl: "https://www.youtube.com/watch?v=4VqmGXwpLqc",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
            {
              id: 3,
              title: "Quick Sort",
              type: "video",
              duration: "28 min",
              videoUrl: "https://www.youtube.com/watch?v=Hoixgm4-P4M",
              thumbnail: "/placeholder.svg?height=120&width=200",
              completed: false,
            },
          ],
        },
      ],
      syllabus: [
        "Arrays and String Manipulation",
        "Linked Lists Implementation",
        "Stacks and Queues",
        "Trees and Binary Search Trees",
        "Sorting Algorithms",
        "Searching Algorithms",
        "Graph Algorithms",
        "Dynamic Programming",
        "Greedy Algorithms",
        "Advanced Data Structures",
      ],
      prerequisites: ["Basic programming knowledge", "Understanding of loops and functions"],
      learningOutcomes: [
        "Implement fundamental data structures",
        "Analyze algorithm complexity",
        "Solve coding interview problems",
        "Optimize code performance",
      ],
    },
    {
      _id: "web-development",
      title: "Full Stack Web Development",
      description: "Complete web development course covering frontend and backend technologies",
      instructor: "Prof. Michael Chen",
      duration: "16 weeks",
      level: "Beginner",
      rating: 4.7,
      studentsEnrolled: 8930,
      price: 149,
      originalPrice: 299,
      thumbnail: "/placeholder.svg?height=200&width=300",
      tags: ["Web Development", "JavaScript", "React", "Node.js"],
      category: "Web Development",
      isActive: true,
      comingSoon: true,
      concepts: [],
      syllabus: [
        "HTML5 & CSS3 Fundamentals",
        "JavaScript ES6+",
        "React.js Development",
        "Node.js & Express",
        "Database Integration",
        "Authentication & Security",
        "Deployment & DevOps",
      ],
      prerequisites: ["Basic computer skills"],
      learningOutcomes: [
        "Build responsive web applications",
        "Create RESTful APIs",
        "Implement user authentication",
        "Deploy applications to cloud",
      ],
    },
    {
      _id: "machine-learning",
      title: "Machine Learning Fundamentals",
      description: "Introduction to machine learning algorithms and applications",
      instructor: "Dr. Emily Rodriguez",
      duration: "14 weeks",
      level: "Intermediate",
      rating: 4.9,
      studentsEnrolled: 6750,
      price: 199,
      originalPrice: 399,
      thumbnail: "/placeholder.svg?height=200&width=300",
      tags: ["Machine Learning", "Python", "AI", "Data Science"],
      category: "Artificial Intelligence",
      isActive: true,
      comingSoon: true,
      concepts: [],
      syllabus: [
        "Introduction to ML",
        "Supervised Learning",
        "Unsupervised Learning",
        "Neural Networks",
        "Deep Learning Basics",
        "Model Evaluation",
        "Real-world Applications",
      ],
      prerequisites: ["Python programming", "Basic statistics", "Linear algebra"],
      learningOutcomes: [
        "Understand ML algorithms",
        "Build predictive models",
        "Evaluate model performance",
        "Apply ML to real problems",
      ],
    },
    {
      _id: "mobile-development",
      title: "Mobile App Development",
      description: "Build native and cross-platform mobile applications",
      instructor: "Alex Thompson",
      duration: "12 weeks",
      level: "Intermediate",
      rating: 4.6,
      studentsEnrolled: 4320,
      price: 129,
      originalPrice: 259,
      thumbnail: "/placeholder.svg?height=200&width=300",
      tags: ["Mobile Development", "React Native", "Flutter", "iOS", "Android"],
      category: "Mobile Development",
      isActive: true,
      comingSoon: true,
      concepts: [],
      syllabus: [
        "Mobile Development Basics",
        "React Native Fundamentals",
        "Flutter Development",
        "Native Features Integration",
        "State Management",
        "API Integration",
        "App Store Deployment",
      ],
      prerequisites: ["JavaScript knowledge", "Basic programming concepts"],
      learningOutcomes: [
        "Build cross-platform apps",
        "Integrate device features",
        "Publish to app stores",
        "Optimize app performance",
      ],
    },
    {
      _id: "cloud-computing",
      title: "Cloud Computing & AWS",
      description: "Master cloud computing concepts and AWS services",
      instructor: "David Kumar",
      duration: "10 weeks",
      level: "Intermediate",
      rating: 4.8,
      studentsEnrolled: 5680,
      price: 179,
      originalPrice: 359,
      thumbnail: "/placeholder.svg?height=200&width=300",
      tags: ["Cloud Computing", "AWS", "DevOps", "Infrastructure"],
      category: "Cloud Computing",
      isActive: true,
      comingSoon: true,
      concepts: [],
      syllabus: [
        "Cloud Computing Fundamentals",
        "AWS Core Services",
        "EC2 & Load Balancing",
        "Storage Solutions",
        "Database Services",
        "Security & IAM",
        "Monitoring & Optimization",
      ],
      prerequisites: ["Basic networking knowledge", "Linux fundamentals"],
      learningOutcomes: [
        "Deploy scalable applications",
        "Manage cloud infrastructure",
        "Implement security best practices",
        "Optimize cloud costs",
      ],
    },
    {
      _id: "cybersecurity",
      title: "Cybersecurity Essentials",
      description: "Learn cybersecurity fundamentals and ethical hacking",
      instructor: "Lisa Wang",
      duration: "8 weeks",
      level: "Beginner",
      rating: 4.7,
      studentsEnrolled: 3450,
      price: 159,
      originalPrice: 319,
      thumbnail: "/placeholder.svg?height=200&width=300",
      tags: ["Cybersecurity", "Ethical Hacking", "Network Security"],
      category: "Security",
      isActive: true,
      comingSoon: true,
      concepts: [],
      syllabus: [
        "Security Fundamentals",
        "Network Security",
        "Web Application Security",
        "Cryptography Basics",
        "Penetration Testing",
        "Incident Response",
        "Security Compliance",
      ],
      prerequisites: ["Basic networking", "Computer fundamentals"],
      learningOutcomes: [
        "Identify security vulnerabilities",
        "Implement security measures",
        "Conduct security assessments",
        "Respond to security incidents",
      ],
    },
  ]
  
  module.exports = coursesData
  